[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"

[project]
name = "powersniffer"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "aio-pika>=9.5.6",
    "bleak>=1.1.1",
    "pymongo>=4.18.2",
]

[project.scripts]
powersniffer-collector = "powersniffer.entrypoints.collector:run"
powersniffer-storage-consumer = "powersniffer.entrypoints.storage_consumer:run"