- name: Deploy new app version
  hosts: raspberries
  gather_facts: false
  tasks:
    - name: Get old app pid
      block:
        - name: Read old app pid
          ansible.builtin.command: cat app.pid
          register: pid_cmd
          args:
            chdir: "{{ active_release_link }}"

        - name: Show old app pid
          ansible.builtin.debug:
            msg: "{{pid_cmd.stdout}}"

        - name: Register old pid as var
          ansible.builtin.set_fact:
            old_pid: "{{pid_cmd.stdout}}"

        - name: Check old pid format
          ansible.builtin.debug:
            msg: "Old PID {{old_pid}} is not valid!"
          when: (old_pid | regex_search("^\d+$")) != old_pid

    - name: Gen release path
      ansible.builtin.include_tasks: tasks/gen_release_path.yml

    - name: Make shadow copy
      ansible.builtin.command:
        cmd: "cp -L -r {{active_release_link}} {{release_path}}"

    - name: Fetch latest state from git main
      ansible.builtin.command:
        cmd: git pull
      args:
        chdir: "{{release_path}}"

    - name: Render application config
      ansible.builtin.template:
        src: "{{playbook_dir}}/../templates/config.toml.j2"
        dest: "{{ release_path }}/config.toml"
        mode: "0644"

    - name: UV sync
      ansible.builtin.command: "~/.local/bin/uv --directory {{release_path}} sync"

    - name: Run new app instance
      ansible.builtin.include_tasks: tasks/run_app.yml

    - name: Stop old instance
      ansible.builtin.shell:
        cmd: "kill {{old_pid}}"
      args:
        executable: /bin/bash
      failed_when: false
      when: (old_pid | regex_search("^\d+$")) == old_pid