- name: Build env
  hosts: raspberries
  tasks:
   - name: Create root directories
     ansible.builtin.include_tasks: tasks/workdir.yml

   - name: UV
     ansible.builtin.include_tasks: tasks/uv.yml

   - name: Make init release
     ansible.builtin.include_tasks: tasks/init_release.yml

   - name: Run app
     ansible.builtin.include_tasks: tasks/runner.yml