# Repo settings
repo_clone_url: git@github.com:stmicroel-avr/powersniffer2.0-dash.git
working_branch: main

# UV packet manager settings
uv_version: 0.12.21
uv_listener_id: powersniffer-listener

# Root directories path
app_root: /opt/apps/psniffer-dash
logs_dir: "{{ app_root }}/logs"
releases_dir: "{{ app_root }}/releases"
active_release_link: "{{ app_root }}/current"
releases_date_pattern: "%Y-%m-%d_%s"

# Bluetooth device info
bt_host_name: JDY-33-SPP
bt_host_addr: 24:F7:3E:37:07:28

# RMQ
rabbitmq_vhost: psniffer