# Repo settings
repo_clone_url: git@github.com:stmicroel-avr/powersniffer2.0-dash.git
working_branch: main

# UV packet manager settings
uv_version: 0.12.21
uv_collector_cmd_id: powersniffer-collector

# Root directories path
app_root: /opt/apps/psniffer-dash
logs_dir: "{{ app_root }}/logs"
releases_dir: "{{ app_root }}/releases"
active_release_link: "{{ app_root }}/current"
releases_date_pattern: "%Y-%m-%d_%s"

# Bluetooth device info
bt_host_name: JDY-33-SPP
bt_host_addr: 24:F7:3E:37:07:28

# RMQ
rmq_vhost: psniffer
rmq_app_user: psniffer-user
rmq_app_exchange_name: psniffer-ex
rmq_app_mongo_queue: psniffer-q-mongo

# MongoDB
mongodb_deb_link: "https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/9.0/multiverse/binary-arm64/mongodb-org-server_9.0.2_arm64.deb"
mongodb_app_user: psniffer-app
mongodb_app_dbname: "psniffer-metrics"
