- name: Build release path
  ansible.builtin.set_fact:
    release_path: "{{ releases_dir }}/{{ now(fmt=releases_date_pattern) }}"

- name: Show release path
  ansible.builtin.debug:
    msg: "Release path {{release_path}}"
