- name: Start new app instance
  ansible.builtin.shell: |
    nohup {{ ansible_env.HOME }}/.local/bin/uv run {{uv_listener_id}} > app.log 2>&1 &
    echo $! > app.pid
  args:
    chdir: "{{ active_release_link }}"
    executable: /bin/bash

