- name: Get old app pid
  block:
    - name: Read old app pid
      ansible.builtin.command: cat app.pid
      register: pid_cmd
      args:
        chdir: "{{ active_release_link }}"

    - name: Show old app pid
      ansible.builtin.debug:
        msg: "{{pid_cmd.stdout}}"

    - name: Register old pid as var
      ansible.builtin.set_fact:
        old_pid: "{{pid_cmd.stdout}}"

    - name: Check old pid format
      ansible.builtin.debug:
        msg: "Old PID {{old_pid}} is not valid!"
      when: (old_pid | regex_search("^\d+$")) != old_pid

- name: Make release path
  block:
  - name: Get current date
    ansible.builtin.command: date "+{{releases_date_pattern}}"
    register: current_date

  - name: Build release path
    ansible.builtin.set_fact:
      release_path: "{{releases_dir}}/{{current_date.stdout}}"

  - name: Show release path
    ansible.builtin.debug:
      msg: "Release path {{release_path}}"

- name: Make shadow copy
  ansible.builtin.command:
    cmd: "cp -L -r {{active_release_link}} {{release_path}}"

- name: Fetch latest state from main
  ansible.builtin.command:
    cmd: git pull
  args:
    chdir: "{{release_path}}"